"""Repository hygiene checks.

Three standing checks keep the repository legible for external review: every
text file stays within a fixed character set (printable ASCII plus the
typographic punctuation used in the documentation), no date-like token may
fall after the era close (2026-06-30), and the README carries the agreed
data-provenance wording.
"""

from __future__ import annotations

import re

# Character set: printable ASCII, the common whitespace controls, and the
# typographic glyphs used in the documentation. Anything else (a control
# byte or a character from another script) fails the check.
_TYPOGRAPHIC_GLYPHS = {
    "\u00b7",  # middle dot
    "\u00d7",  # multiplication sign
    "\u2013",  # en dash
    "\u2014",  # em dash
    "\u2026",  # horizontal ellipsis
    "\u2192",  # rightwards arrow
    "\u2212",  # minus sign
    "\u2265",  # greater-than or equal to
    "\u2500",  # box drawing light horizontal
    "\u2502",  # box drawing light vertical
    "\u2518",  # box drawing light up and left
    "\u25b6",  # black right-pointing triangle
    "\u25bc",  # black down-pointing triangle
    "\u25c0",  # black left-pointing triangle
}

_TEXT_SUFFIXES = {".py", ".md", ".yaml", ".json", ".toml", ".csv", ".txt"}
_SKIP_DIRS = {"venv", ".git", "__pycache__", ".pytest_cache"}

_DATE_TOKEN = re.compile(r"\d{4}-\d{2}-\d{2}")
_ERA_CLOSE = "2026-06-30"

_README_WORDING = (
    "synthetic case records for method demonstration and reproducibility,"
    " generated by a seeded, deterministic generator"
)


def _repo_files(repo):
    for path in sorted(repo.rglob("*")):
        if not path.is_file():
            continue
        if any(part in _SKIP_DIRS for part in path.parts):
            continue
        yield path


def _readable_text(path):
    try:
        return path.read_text(encoding="utf-8")
    except UnicodeDecodeError:
        return None


def _char_allowed(ch):
    if ch in ("\t", "\n", "\r"):
        return True
    if 0x20 <= ord(ch) <= 0x7E:
        return True
    return ch in _TYPOGRAPHIC_GLYPHS


def test_text_files_stay_within_the_permitted_character_set(repo):
    offenders = []
    for path in _repo_files(repo):
        if path.suffix not in _TEXT_SUFFIXES:
            continue
        text = _readable_text(path)
        if text is None:
            offenders.append((str(path.relative_to(repo)), "not valid UTF-8"))
            continue
        for ch in text:
            if not _char_allowed(ch):
                offenders.append((str(path.relative_to(repo)), f"U+{ord(ch):04X}"))
                break
    assert offenders == [], f"characters outside the permitted set: {offenders}"


def test_no_date_token_after_the_era_close(repo):
    offenders = []
    for path in _repo_files(repo):
        if path.suffix not in _TEXT_SUFFIXES:
            continue
        text = _readable_text(path)
        if text is None:
            continue
        for match in _DATE_TOKEN.findall(text):
            if match > _ERA_CLOSE:
                offenders.append((str(path.relative_to(repo)), match))
    assert offenders == [], f"post-era dates found: {offenders}"


def test_readme_carries_the_agreed_data_wording(repo):
    readme = (repo / "README.md").read_text(encoding="utf-8")
    normalized = " ".join(readme.split())
    assert _README_WORDING in normalized
